/*
 * WHOOP API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Whoop.Sdk.Client;
using Whoop.Sdk.Client.Auth;
using Whoop.Sdk.Model;

namespace Whoop.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISleepApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the sleep for the specified ID
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Sleep</returns>
        Sleep GetSleepById(long sleepId, int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the sleep for the specified ID
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Sleep</returns>
        ApiResponse<Sleep> GetSleepByIdWithHttpInfo(long sleepId, int operationIndex = 0);
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaginatedSleepResponse</returns>
        PaginatedSleepResponse GetSleepCollection(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0);

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaginatedSleepResponse</returns>
        ApiResponse<PaginatedSleepResponse> GetSleepCollectionWithHttpInfo(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISleepApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the sleep for the specified ID
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Sleep</returns>
        System.Threading.Tasks.Task<Sleep> GetSleepByIdAsync(long sleepId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get the sleep for the specified ID
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Sleep)</returns>
        System.Threading.Tasks.Task<ApiResponse<Sleep>> GetSleepByIdWithHttpInfoAsync(long sleepId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaginatedSleepResponse</returns>
        System.Threading.Tasks.Task<PaginatedSleepResponse> GetSleepCollectionAsync(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 
        /// </summary>
        /// <remarks>
        /// Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </remarks>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaginatedSleepResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<PaginatedSleepResponse>> GetSleepCollectionWithHttpInfoAsync(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ISleepApi : ISleepApiSync, ISleepApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class SleepApi : ISleepApi
    {
        private Whoop.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="SleepApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SleepApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SleepApi"/> class.
        /// </summary>
        /// <returns></returns>
        public SleepApi(string basePath)
        {
            this.Configuration = Whoop.Sdk.Client.Configuration.MergeConfigurations(
                Whoop.Sdk.Client.GlobalConfiguration.Instance,
                new Whoop.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Whoop.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Whoop.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Whoop.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SleepApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public SleepApi(Whoop.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Whoop.Sdk.Client.Configuration.MergeConfigurations(
                Whoop.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Whoop.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Whoop.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Whoop.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="SleepApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public SleepApi(Whoop.Sdk.Client.ISynchronousClient client, Whoop.Sdk.Client.IAsynchronousClient asyncClient, Whoop.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Whoop.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Whoop.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Whoop.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Whoop.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Whoop.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        ///  Get the sleep for the specified ID
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Sleep</returns>
        public Sleep GetSleepById(long sleepId, int operationIndex = 0)
        {
            Whoop.Sdk.Client.ApiResponse<Sleep> localVarResponse = GetSleepByIdWithHttpInfo(sleepId);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the sleep for the specified ID
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Sleep</returns>
        public Whoop.Sdk.Client.ApiResponse<Sleep> GetSleepByIdWithHttpInfo(long sleepId, int operationIndex = 0)
        {
            Whoop.Sdk.Client.RequestOptions localVarRequestOptions = new Whoop.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Whoop.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Whoop.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("sleepId", Whoop.Sdk.Client.ClientUtils.ParameterToString(sleepId)); // path parameter

            localVarRequestOptions.Operation = "SleepApi.GetSleepById";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<Sleep>("/v1/activity/sleep/{sleepId}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSleepById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get the sleep for the specified ID
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Sleep</returns>
        public async System.Threading.Tasks.Task<Sleep> GetSleepByIdAsync(long sleepId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Whoop.Sdk.Client.ApiResponse<Sleep> localVarResponse = await GetSleepByIdWithHttpInfoAsync(sleepId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get the sleep for the specified ID
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sleepId">ID of the sleep to retrieve</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Sleep)</returns>
        public async System.Threading.Tasks.Task<Whoop.Sdk.Client.ApiResponse<Sleep>> GetSleepByIdWithHttpInfoAsync(long sleepId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Whoop.Sdk.Client.RequestOptions localVarRequestOptions = new Whoop.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Whoop.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Whoop.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("sleepId", Whoop.Sdk.Client.ClientUtils.ParameterToString(sleepId)); // path parameter

            localVarRequestOptions.Operation = "SleepApi.GetSleepById";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Sleep>("/v1/activity/sleep/{sleepId}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSleepById", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>PaginatedSleepResponse</returns>
        public PaginatedSleepResponse GetSleepCollection(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0)
        {
            Whoop.Sdk.Client.ApiResponse<PaginatedSleepResponse> localVarResponse = GetSleepCollectionWithHttpInfo(limit, start, end, nextToken);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of PaginatedSleepResponse</returns>
        public Whoop.Sdk.Client.ApiResponse<PaginatedSleepResponse> GetSleepCollectionWithHttpInfo(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0)
        {
            Whoop.Sdk.Client.RequestOptions localVarRequestOptions = new Whoop.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Whoop.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Whoop.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (start != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "start", start));
            }
            if (end != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "end", end));
            }
            if (nextToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "nextToken", nextToken));
            }

            localVarRequestOptions.Operation = "SleepApi.GetSleepCollection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<PaginatedSleepResponse>("/v1/activity/sleep", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSleepCollection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        ///  Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of PaginatedSleepResponse</returns>
        public async System.Threading.Tasks.Task<PaginatedSleepResponse> GetSleepCollectionAsync(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Whoop.Sdk.Client.ApiResponse<PaginatedSleepResponse> localVarResponse = await GetSleepCollectionWithHttpInfoAsync(limit, start, end, nextToken, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        ///  Get all sleeps for a user, paginated. Results are sorted by start time in descending order.
        /// </summary>
        /// <exception cref="Whoop.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit">Limit on the number of sleeps returned (optional, default to 10)</param>
        /// <param name="start">Return sleeps that occurred after or during (inclusive) this time. If not specified, the response will not filter sleeps by a minimum time. (optional)</param>
        /// <param name="end">Return sleeps that intersect this time or ended before (exclusive) this time. If not specified, &#x60;end&#x60; will be set to &#x60;now&#x60;. (optional)</param>
        /// <param name="nextToken">Optional next token from the previous response to get the next page. If not provided, the first page in the collection is returned (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (PaginatedSleepResponse)</returns>
        public async System.Threading.Tasks.Task<Whoop.Sdk.Client.ApiResponse<PaginatedSleepResponse>> GetSleepCollectionWithHttpInfoAsync(int? limit = default(int?), DateTime? start = default(DateTime?), DateTime? end = default(DateTime?), string? nextToken = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {

            Whoop.Sdk.Client.RequestOptions localVarRequestOptions = new Whoop.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Whoop.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Whoop.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (start != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "start", start));
            }
            if (end != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "end", end));
            }
            if (nextToken != null)
            {
                localVarRequestOptions.QueryParameters.Add(Whoop.Sdk.Client.ClientUtils.ParameterToMultiMap("", "nextToken", nextToken));
            }

            localVarRequestOptions.Operation = "SleepApi.GetSleepCollection";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (OAuth) required
            // oauth required
            if (!localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                if (!string.IsNullOrEmpty(this.Configuration.AccessToken))
                {
                    localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
                }
                else if (!string.IsNullOrEmpty(this.Configuration.OAuthTokenUrl) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientId) &&
                         !string.IsNullOrEmpty(this.Configuration.OAuthClientSecret) &&
                         this.Configuration.OAuthFlow != null)
                {
                    localVarRequestOptions.OAuth = true;
                }
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<PaginatedSleepResponse>("/v1/activity/sleep", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSleepCollection", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
